navikt/melosys-eessi

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/SedStatus.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java
Sorterer seder etter status når vi skal finne tidl. sed med type.
Sedene sorteres etter rekkefølge på enum-verdier i SedStatus.
> MELOSYS-3438 - Sorter sed ved oppdatering

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/SafConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/SafConsumerProducer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/dto/GraphQLError.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/dto/GraphQLQueryData.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/dto/GraphQLResponse.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/dto/SafQueryData.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/saf/dto/Tilleggsopplysning.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalpostkobling/JournalpostSedKoblingService.java
- melosys-eessi-app/src/main/resources/application-local.properties
- melosys-eessi-app/src/main/resources/application.yml
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/saf/SafConsumerTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/journalpostkobling/JournalpostSedKoblingServiceTest.java
- melosys-eessi-app/src/test/resources/mock/saf-err.json
- melosys-eessi-app/src/test/resources/mock/saf.json
Grunnet at eux-case-store bare holder på informasjon for siste journalpost som har kommet inn på en sak, integrerer vi mot SAF for å kunne se på tilleggsopplysninger til en journalpost - hvor EESSI-applikasjonene alltid lagrer rinaSakId på.
> Integrerer mot SAF for å kunne hente ut tilleggsopplysninger for journalpost

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxTokenContextService.java
- melosys-eessi-app/src/main/resources/application.yml
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
Legger til variabel for feature-toggling av Norge sin eessi-ready status på enkelte BUC-er. Det skal returneres en tom liste ved henting av mottakinstitusjoner når Norge ikke er påkoblet den aktuelle BUCen
> Håndter at melosys ikke er EESSI-ready

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
Integrasjon mot eux for å legge til vedlegg var litt vel gammel, og melosys hadde egentlig aldri brukt den. 
Etter en titt på eux-rina-api så jeg at tjenesten krevde multipart_form_data som content_type. 
Fikser feil ved videresending av søknad.
> Fikser integrasjon mot eux for å legge til vedlegg på en SED

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/BucController.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/SedVedlegg.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/Vedlegg.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java
Ref https://github.com/navikt/melosys-api/pull/133
Er gjort en liten quick-fix i `EuxConsumer` ved formatering av filnavn. Går ikke helt topp å sende ett vedlegg med æøå - mistenker at det har noe med å gjøre at dette skal sendes med i url-en, og at filnavnet da blir feiltolket av `eux-rina-api`..
> Melosys 3744  vedlegg filnavn sed

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/BucController.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/SedDataDto.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedSendtConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/exception/MappingException.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/exception/NotFoundException.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/exception/SecurityException.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/exception/ValidationException.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/behandling/BehandleSedMottattService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/identifisering/PersonSok.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/OpprettUtgaaendeJournalpostService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/A1GrunnlagMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/PostnummerMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/SedMapperFactory.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A002Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A003Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A004Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A008Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A010Mapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001MapperTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A003MapperTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009MapperTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A010MapperTest.java
- melosys-eessi-app/src/test/resources/mock/sedDataDtoStub.json
Fikser mapping til arbeidsgiver til SED - slik at disse settes i enkelte felt ut fra hvilket lovvalgsland som er valgt.
Gjør også om en del exceptions til unchecked, for å bedre kunne utnytte streams i samme slengen. Hovedsakelig exceptions som kastes ved validerings-feil i mapping.
> Melosys 3761  arbeidsgiver lovvalgsland sed

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/Adresse.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/sed_grunnlag/SedGrunnlagMapperA003.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/sed_grunnlag/SedGrunnlagMapperA003Test.java
Vi har noen behandlinger i q2 som har feilet fordi vi fikk NPE når arbeidsgivers adresse ikke er satt. Legger til nullsjekk ved henting og mapping av arbeidsgivers adresse.
> BUGFIX - NPE ved tom adresse for arbeidsgiver

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BucUtils.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/Konstanter.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/X001Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A011Mapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/models/buc/BucUtilsTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java
Fra story; 
>Etter 13. juni må alle SEDer i nye BUCer opprettes med v4.2. Gamle BUCer hvor det allerede er utvekslet 4.1 må fortsette utveksling i v4.1
Jeg oppdaterer også default SED-versjon til å være 4.2
> Melosys 3700  sed v42

- melosys-eessi-app/src/main/resources/application.yml
Det står ikke i loggen hvor stor fila som feila var, men håper det holder å doble. Hvis ikke får jeg prøve å se om jeg kan få logga det på en eller annen måte. 
Har testa lokalt med Postman.
> Sett maks fil+request-størrelse til dobbelt av default

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/BucController.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
Krever tilsvarende endringer i `melosys-api`. Formålet er å unngå flere API-kall i `melosys-web` eller `melosys-api` for å hente ut liste med mottakerinstitusjoner for alle valgte land.
> Støtt henting av mottakerinstitusjoner for flere land per buc

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/SedType.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/SED.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/identifisering/PersonKontroller.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/identifisering/PersonSok.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/identifisering/PersonSokTest.java
- melosys-eessi-app/src/test/resources/mock/sedX001.json
Fiks for å kunne opprette journalpost av en X-SED, hvor det ikke er opprettet en sak av tilhørende BUC enda. Disse har til nå feilet med en nullpointer, og blitt restartet manuelt etter en sak har blitt opprettet.
Sjekker ikke statsborgerskap ved identifisering av en X-SED, da dette ikke er mulig å oppgi her. Ved jfr-oppgave for en X-SED vil uansett en saksbehandler måtte gå inn og behandle den.
> Mottak X-SED uten sakstilknytning i Melosys

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
Iso3 -> Iso2 for statsløs mappes XXX -> XS (XS brukes av RINA)
Hører sammen med fiks i melosys-api: https://github.com/navikt/melosys-api/pull/423
> Bugfix - Støtter mapping av statsløst statsborgerskap

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLQuery.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLUtils.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/HarMetadata.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLEndring.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLFoedsel.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLFolkeregisterPersonstatus.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLMetadata.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLNavn.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/tps/TpsService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/person/PersonModell.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/identifisering/PersonKontroller.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/PDLServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/identifisering/PersonSokTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/tps/TpsServiceTest.java
- melosys-eessi-app/src/test/resources/mock/pdl_hent_person.json
Henter ut siste opplysning fra responsen til PDL.hentPerson ved å se på metadataen til ønsket opplysning. Har her gjort en antagelse om at hvis en opplysning har en endring med type "OPPHOER" så vil ikke denne opplysningen komme med i responsen, da vi ikke spør om historikk. Har enda til gode å få testet eller bekreftet dette på en annen måte.
EDIT: fikk avklart i #mfn på Slack, var som jeg antok 🙂
> MELOSYS-4411:  hentPerson mapping

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLQuery.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLHentIdenterResponse.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLIdent.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLIdentliste.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/tps/TpsService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/PDLConsumerTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/PDLServiceTest.java
- melosys-eessi-app/src/test/resources/mock/pdl_hent_identliste.json
Implementasjon av PDL sin hentIdenter-spørring.
Spørringen tar i mot hvilken som helst ID som input. Så det spiller ingen rolle om vi spør om alle identer basert på en aktørid, fnr, dnr eller NPID (NAV-PersonID) som input til tjenesten. Dette gjelder for øvrig alle PDL-tjenester.
> Melosys 4440 pdl hent identer

- melosys-eessi-app/pom.xml
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/identifisering/FnrUtils.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/identifisering/PersonIdentifiseringService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/identifisering/FnrUtilsTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/identifisering/PersonIdentifiseringServiceTest.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestIT.java
- pom.xml
Feks når norsk ident er oppgitt med en bindestrek mellom fødselsdato og personnummer.
Legger til en avhengighet `bekk-nocommons` som har validering for norsk ident.
> Håndterer mottak av SED hvor norsk ident er oppgitt i feil format

- .github/workflows/deploy.yaml
- deploy/nais.yaml
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/SwaggerConfig.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/KopierBucController.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/Participant.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/buc/KopierBucService.java
- melosys-eessi-app/src/main/resources/application.yml
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/buc/KopierBucServiceTest.java
Grunnet skadede BUCer ved at vi automatisk har forsøkte å sende SED for kort tid etter opprettelse, må vi sende disse SEDer på nytt, i nye BUCer. 
Lager et enkelt endepunkt som tar i mot en liste av rina-saker (saksnummer), og kopierer over første SED i en BUC til en ny BUC.
> MELOSYS-4567 - kopier buc

- .editorconfig
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BucIdentifiseringService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretHendelse.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonSok.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/RestUtils.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/oppgave/OppgaveConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/oppgave/OppgaveConsumerProducer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/oppgave/OppgaveDto.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedHendelse.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/SystemContextRequestFilter.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/oppgave/OppgaveService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/oppgave/OppgaveConsumerTest.java
Småfiksing ifbm MELOSYS-4435. Hovedsakelig to ting som manglet:
- Sette RINA-saksnummer som metadata i oppgaven som opprettes til ID og Fordeling
- Http-method PATCH støttes ikke "ut av boksen" av Java, og kall med PATCH feilet med OppgaveConsumer sin RestTemplate. Hovedgrunnen til dette er nok at melosys-eessi ikke lar den bli konfigurert av Spring. Jeg skrev om testene for å fremprovosere problemet (noe som ikke gikk..), og da skrev jeg like gjerne om fra RestTemplate til WebClient mens jeg var i gang.. 🙃 
Også litt småforbedringer med f.eks. logging av korrelasjonsid mot Oppgave og ignorering av enkelte felter fra autogenerert toString av Lombok.
> Fix for maks én identifisering oppgave

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SakController.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/buc/LukkBucService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/buc/LukkBucServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedDataStub.java
Når er RINA-sak er arkivert, så kan ikke Melosys hente den, og det er heller ingen mulighet for å endre tilstanden på BUCen. Innfører da en metode som fanger exception og returnerer Optional ved forsøk på å hente ned en BUC.
> No jira fix arkivert rinasak

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BucIdentifisertService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/SedIdentifiseringService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/event/BucIdentifisertEvent.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/BucIdentifisert.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/repository/BucIdentifisertRepository.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/OpprettInngaaendeJournalpostService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/OpprettUtgaaendeJournalpostService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/BucIdentifisertEventListener.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sak/ArkivsakService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sak/SakService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/saksrelasjon/SaksrelasjonOpprettetEventListener.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/saksrelasjon/SaksrelasjonService.java
- melosys-eessi-app/src/main/resources/db/migration/V2_3__buc_identifisert.sql
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/BucIdentifisertServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/SedIdentifiseringServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/behandling/SedMottakServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/joark/OpprettInngaaendeJournalpostServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/joark/OpprettUtgaaendeJournalpostServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sak/ArkivsakServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sak/SakServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/saksrelasjon/SaksrelasjonServiceTest.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedMottakTestIT.java
Lagrer ident identifisert for BUC sammen med saksnummeret. Dette i hovedsak for å unngå et race-condition hvor flere identifiseringsevent behandles samtidig, men også for å gi melosys-eessi mer eierskap til selve identifiseringen av BUCen, hvor den når har lent seg på å hente ut dette fra arkivsaken.
Også litt småoppussing rundt omkring.
> Melosys 4435 lagre ident identifisert for BUC

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/oppgave/OppgaveConsumer.java
Fjerner loggnivå info på hent oppgave slik at vi ikke spammer med logging og refaktorering av logikk i identifiseringsfilter
> No jira refaktor oppgave endret consumer

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringsKontrollBegrunnelse.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringsKontrollResultat.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonKontroller.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonSokMetrikker.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollServiceTest.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/OppgaveEndretMottakTestIT.java
Overstyrer identifiseringskontroll mot sed dersom ID og Fordeling har oversendt oppgave 2 ganger
> Melosys 4877 endring sed inn tilpassing av automatiske sed kontroller av identifiseringsfilter

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/repository/BucIdentifiseringOppgRepository.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollServiceTest.java
oppdaterer versjonsnummer på identifisersoppgave og ikke lagre ny rad i tabellen. I tillegg reduserer vi antallet vi sjekker mot til 2 da dette vil være riktigere når vi setter versjon = 1 ved mottak av sed
> MEL-4877-Legger til updateVersjonNumberBy1 i JPArepo for å oppdatere versjon

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/SedDataDto.java
[MELOSYS-5053](https://jira.adeo.no/browse/MELOSYS-5053)
Fikser feil ved forhåndsvisning i EESSI der man har brukt findFirst litt tvetydelig. Forårsaket NullpointerException fordi findFirst traff på null.
https://stackoverflow.com/questions/32466799/why-does-findfirst-throw-a-nullpointerexception-if-the-first-element-it-finds
> Filtrerer bort null-verdier før findFirst i finnLovvalgsland()

- deploy/nais.yaml
Melosys-eessi manglet miljøvariabel for å overstyre defaultverdier til JVM heap size. Siden vi egentlig ikke vet hvor mye minne melosys-eessi behøver, må vi ha en høy verdi, og justere det ned senere. 
Både JVM heap size og pod-minne er satt til 2gb. JVM heap size burde alltid være mindre enn total allokert minne. Sett JVM heap size til 2gb, og Pod-minne til 2.5gb. Vi må samle data om hvor mye melosys-eessi bruker over tid, og justere det et par måneder etterpå.
https://jira.adeo.no/browse/MELOSYS-5198
> 5198: Setter pod memory limit høyere enn JVM heap size

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertServiceTest.java
Tidligere relevant PR: https://github.com/navikt/melosys-eessi/pull/478
https://jira.adeo.no/browse/MELOSYS-5219
https://nav-it.slack.com/archives/CPSMP2GKT/p1659370762184569
> 5219 Ignorerer SED med X100, også når man identifiserer alle SED for BUC

- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestConfig.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/KafkaAdminTjenesteTestIT.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/OppgaveEndretMottakTestIT.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedMottakTestIT.java
- melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedSendtTestIT.java
- melosys-eessi-test/src/test/java/no/nav/melosys/utils/KafkaTestConfig.java
- melosys-eessi-test/src/test/resources/application-test.yaml
Av og til feiler komptester med "Socket server failed to bind to localhost:*****: Address already in use."
Det er nok fordi EmbeddedKafkaBroker ble delt mellom testene.
Legg til @EmbeddedKafka på ComponentTestBase i stedet. Litt opprydding i tillegg
Skal løse denne feilen: https://github.com/navikt/melosys-eessi/runs/7626164191?check_suite_focus=true.
Løser dessverre ikke https://github.com/navikt/melosys-eessi/runs/7648286935?check_suite_focus=true fra `KafkaAdminTjenesteTestIT`
> @EmbeddedKafka for hver komptest

- deploy/nais.yaml
https://doc.nais.io/nais-application/ingress/#custom-max-body-size
NAIS gikk fra traefik til nginx og dette må settes
for å unngå 413 Payload Too Large.
100M skal være maks i Rina
> Ingress annotations for vedlegg

- .github/workflows/deploy-dev-manuelt.yaml
- .github/workflows/deploy-dev.yaml
- .github/workflows/pull-request.yaml
- Dockerfile
- pom.xml
Trenger java 17 for nyere versjon av token support som brukes til [azure ad](https://github.com/navikt/melosys-eessi/pull/487)
> Bump Java til 17

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/FraSedA003Mapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA009.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA010.java
Ref: https://jira.adeo.no/browse/MELOSYS-5268
Lagt til logging i sedErEndring for A003, A009, og A010 for å sikre at vi kan feilsøke nåværende og potensielt fremtidige feil som følge av kompleksiteten av hvilke verdier vi kan forvente på disse.
> 5268 Lagt til logging

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerProducer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.java
- melosys-eessi-app/src/test/resources/mock/buc.json
- pom.xml
Oppgrade jackson for å støtte med og uten kolon i tidsonen, samt bruk WRITE_DATES_AS_TIMESTAMPS konfiguring av ObjectMapper
https://nav-it.slack.com/archives/CCKCDM0AU/p1671543502995309?thread_ts=1671512526.090249&cid=CCKCDM0AU
> Mer robust parsing av dato

- melosys-eessi-app/src/main/resources/logback-nais.xml
For å unngå at vi får delete log meldinger i kibana som da ikke blir rikitg indeksert https://docs.nais.io/observability/logs/examples/
https://jira.adeo.no/browse/MELOSYS-5603
> Bruk ShortenedThrowableConverter for å redusere stacktrace

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedMottattAdminTjeneste.java
For manuell kjøring av sed mottatt
Blir nå først brukt til å få inn ting som ikke lengre ligger i kafka, men vi har i logger
https://jira.adeo.no/browse/MELOSYS-5856
> Legg til SedMottattAdminTjeneste

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonSok.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/PersonFasade.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostapiConfiguration.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxTokenContextService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/JournalpostService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/PersonSokTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostapiConsumerTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/PDLServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/joark/JournalpostServiceTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.java
Får ikke reprodusert akseptansekriterie: 
```
2) Når vi mottar en BUC i RINA der melosys-eessi ikke klarer å hente DNR eller FNR fra PDL, men vi kun får NPID
og personen både er registrert med NPID og DNR/FNR
Så skal melosys-eessi opprette en journalføringsoppgave som overføres til ID-og fordeling(4303) for identifisering. 
```
og det er allerede en test som viser at det går fint å få både NPID og DNR/FNR fra PDL, men `men vi kun får NPID` er sannsynlig det vi får fra PDL og da kan man se på det som samme scenario som akseptansekriterie 1.
https://jira.adeo.no/browse/MELOSYS-5963
> 5963 TOGGLE sende til id og fordeling dersom vi ikke finner folkeregisterident

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/kafkadlq/KafkaDLQService.java
- Dead letter queue tid sist rekjørt
- java:S2229 Methods should not call same-class methods with incompatible "@Transactional" values
> VAKT dlq sett sist rekjoert

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/metrikker/DLQMetrikkerCache.java
Vi resetter ikke queueSizeMap som gjør at gaugen ikke resettes konsekvent for alle typer queueTypes
> VAKT Feil i grafana-gauge pga manglende clearing av map

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
https://jira.adeo.no/browse/MELOSYS-6038
Ingen grunn til å feile med exception her. Fjern også unødvendig bruk av BiMap
> 6038 Ukjent  ISO-3 skal gi ukjent ISO-2 landkode

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedMottattAdminTjeneste.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedMottattConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/kafkadlq/KafkaDLQService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/kontroll/SedMottakAdminTjeneste.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/kontroll/SedMottakAdminTjenesteTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.java
https://nav-it.slack.com/archives/CPSMP2GKT/p1692014324439299
Det var en rekke SED som hadde feilet ved mottak, men blitt tatt vare på i databasen likevel. Mistenker det er pga Transactional har blitt brukt feil. Når man kaller på en Transactional-metode i samme klasse, fungerer da Transactional ikke fordi man ikke har proxy-klasse i selve klassen. 
Kaller nå Transactional-metoden fra utsiden av klassen.
> VAKT: Kall transactional-metode fra utsiden av klassen

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaAivenConfig.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/oppgave/OppgaveEndretService.java
https://github.com/navikt/melosys-eessi/pull/563
Etter å ha satt loggnivå til INFO, og prodsatt, så ser jeg det kommer utrolig mye oppgavehendelse-endringer. Det betyr at det blir gjort litt flere oppgaveendringer enn først tenkt. Slik det er nå, så ignorerer vi visse typer oppgaveendringer når vi først prøver å konsumere meldingen. Siden vi har spesifikke regler på hva vi vil høre på, setter jeg dette på config-nivå, sånn at vi ikke trenger å consumere meldingen i det hele tatt.
> 5962: Legg til bedre filter i konfigurasjonen til konsumering av Aiven topic OppgaveHendelse

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/OppgaveHendelseConsumer.java
Ref. beskrivelsen her: https://github.com/navikt/melosys-eessi/pull/571
Tidligere (se https://github.com/navikt/melosys-eessi/pull/563) så lagde denne loggingen alt for mye støy, ettersom vi konsumerte _alle_ oppgaveendringer. Det ble omtrent 3k oppgaver vi reagerte på per 15 minutt. https://github.com/navikt/melosys-eessi/pull/564 la på filter på config av konsumenten som gjør at vi kun konsumerer de som vi faktisk skal reagere på.
Jeg har fulgt med på loggene og ser at det filteren vår fungerer ganske bra. Det er altså ikke så mange relevante oppgaveendringer vi konsumerer som gjør at logging lager støy nå.
> 5962: Fjern toggle for logging av oppgavehendelser

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapperTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
De klarer ikke å forhåndsvise data vi sender til PDL. Det er fordi vi sender i ISO2-format, mens de forventer i ISO3-format. De ønsker ikke å konvertere selv, og ønsker heller at vi sender riktig data i utgangspunktet.
> 5930 TOGGLE: Send iso3 landkode til PDL-WEB

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapperTest.java
Både _PDL_ og _id og fordeling_ ønsker institusjonsnavn i stedenfor institusjonsid til å være forhåndsutfylt. Derfor bytter vi på det.
> 5930 TOGGLE: Send institusjonsnavn istedenfor id til PDL-WEB

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapper.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
Slik det er i dag: Når land er ukjent (som f.eks. Jugoslavia), så konverterer vi vanligvis til "???" i melosys-eessi før vi får det over til API. Dette er pga felles-kodeverk som har "???" for UKJENT.
Ifm. SED-rekvirering så sender vi en del landkoder til PDL. Disse landkodene forventer PDL at det skal være i ISO3-format. De kjenner ikke til "???" for ukjente land, og opererer istedenfor med XUK. I ISO-3 så er alle koder som starter med X brukerdefinerte. XUK (for "brukerdefinert UKJENT") mener jeg også gir mer mening å ha enn ???.
Sender altså XUK til pdl-web. Akkurat nå er det ingen andre steder som konverterer fra iso2 til iso3, men siden det er en slags global funksjon, lar jeg neste som bruker det velge hvorvidt de skal ha ??? eller XUK.
> 5930 TOGGLE: Send Ukjent landkode til PDL-WEB som XUK og ikke ???

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
Bruker eksisterende funksjon mapTilNavLandkode for å støtte GB og EL:
```
public static String mapTilNavLandkode(String landkode) {
if ("UK".equalsIgnoreCase(landkode)) {
return "GB";
} else if ("EL".equalsIgnoreCase(landkode)) {
return "GR";
}
return landkode;
}
```
https://nav-it.slack.com/archives/CPSMP2GKT/p1700057242620329
> NOJIRA Mapper GB om til UK, og EL om til GR for identrekvisisjon

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapperTest.java
https://jira.adeo.no/browse/MELOSYS-6293
Filtrerer  bort statsborgerskap i SED som er null ved utfylling av DTO til pdl-web.
> 6293: Fiks feil med null i statsborgerskap ved identrekvisisjon

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Vedtak.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/LovvalgSedMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A003MapperTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009MapperTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A010MapperTest.java
Ser tilsynelatende ut som om vi alltid svarer på spørsmålet: "**Er dette et opprinnelig vedtak?**", men at man svarer på ulikt felt avhengig av om det er et opprinnelig vedtak eller ikke. 
- Er svaret **JA** (det er opprinnelig vedtak) setter man `eropprinneligvedtak` = "ja", og `erendringsvedtak` forblir default null. 
- Er svaret **NEI** (det er endringsvedtak) setter man `erendringsvedtak` = "nei", og `eropprinneligvedtak` forblir default null. 
Da gir det også meningen at `eropprinneligvedtak` kun kan være "ja" og null, mens `erendringsvedtak` kun kan være "nei" og null.  
Testet med manuell deploy til Q2 og får ønsket resultat både for endring og opprinnelig vedtak.
https://jira.adeo.no/browse/MELOSYS-6472
> 6472 Erendringsvedtak justering

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedJournalføringAdminTjeneste.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedJournalføringMigreringRapportDto.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedJournalføringMigreringService.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedSendtJournalføringMigrering.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedSendtMigreringRapportDto.java
- melosys-eessi-app/src/main/resources/migrering-sed-sendt-dev.json
- melosys-eessi-app/src/main/resources/migrering-sed-sendt-prod.json
Lastet opp fil for q2 og prod som viser oversikt over alle sendte SED. Disse vil loopes gjennom og sjekket i de miljøene.
> 6601: Kartlegge sendte SED med vedlegg i feilperiode

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaAivenConfig.java
H bucer leses inn for sed mottatt og sendt nå, det betyr at vi får altfor mange seder som vi ikke skulle hatt og journalfører de. Reverter akkurat denne delen av endringen så vi ikke plutselig får det i prod
Må lage en skikkelig løsning etterpå - dette er rask fiks for å unngå problemer
> 6604 Fjerner H buc fra filter da det er for grovt

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/vedlegg/SedMedVedlegg.kt
Filnavn må da være nullable ifm. deserialisering for å kunne kjøre videre med "Vedlegg" som default
> VAKT eux-rina-api gir oss vedlegg med null som tittel 2

- melosys-eessi-app/pom.xml
Dette fikser kotlin json serialisering hvor vi har default verdier når det kommer null fra json.
Testet at dette funker lokalt, og er greit å få dette ut i prod asap. Var litt jobb å få laget en ordentlig test på dette, så det kommer senere.
> 6909 Legg jackson-module-kotlin til i pom

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerProducer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.kt
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.kt
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.kt
- melosys-eessi-app/src/test/resources/mock/sedA009-Kosovo.json
https://jira.adeo.no/browse/MELOSYS-6295
> 6295 Håndtere Kosovo som statsborgerskap ved sending av SED

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapperTest.java
Vi har mottatt en SED med tomt vedlegg.
#team_dokumentløsninger har en validering som forhindrer journalføring av tomt vedlegg
> VAKT Ikke journalfør tomt vedlegg

- pom.xml
Oppgraderer SpringBoot for å luke bort en del sikkerhetsissues.
Blant de er én kritisk:
https://github.com/advisories/GHSA-83qj-6fr2-vhqg - Apache Tomcat: Potential RCE and/or information disclosure and/or information corruption with partial PUT
> G4P NOJIRA: Oppgrader SpringBoot 3.3.5 -> 3.3.11

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/dto/PDLSokCriterion.java
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/PDLServiceTest.java
https://jira.adeo.no/browse/MELOSYS-7268?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel
Person søk søker fortsatt via de gamle feltene til PDL hvor vi søker med stien "person.foedsel.foedselsdato".
Endret stien til å samsvare med nye strukturen til PDL så den blir da "person.foedselsdato.foedselsdato"
> 7268 Søking av PDL fødselsdato på personer

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/KafkaDLQAdminTjeneste.kt
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/ContextHolder.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/ThreadLocalAccessInfo.kt
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/security/ContextHolderIntegrationTest.kt
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/security/ThreadLocalAccessInfoTest.kt
EUX svarer med at vi ikke har tilgang til å gjøre diverse forespørsler. Det er pga OBO-tokens, og våre brukere som ikke har tilgang til Eux/Rina i prod. Derfor kjører vi admin-requests med systemtokens når vi konsumerer eksterne tjenester. Gjenbruker samme system som vi har i melosys-api.
Mulig vi burde få disse tilgangene på sikt, men det er noen grunner til at vi ikke gjør det nå.
- Det vil forsinke DLQs som er i prod i dag, ettersom vi ikke vet hvor lang tid tilgangene  vil ta.
- Det er ikke verre enn dagens løsning. Med forrige PR #733, har vi hatt stor forbedring.
- Gjennom melosys-console blir all historikk av forespørsler lagret for sporbarhet.
> 7389: Ikke bruk OBO-tokens under admin requests

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/KafkaDLQAdminTjeneste.kt
Eksperimenterer med det.. eux-rina-api gir oss 404 på resending, når det har fungert før. Jeg mistenker 404 er en feilmelding som kommer fra dem.
> 8389 G4P VAKT: Fjern systembruker enforcement på resending av SED

- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/JournalpostSedKobling.kt
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalpostkobling/JournalpostSedKoblingService.kt
- melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.kt
- melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.kt
https://nav-it.slack.com/archives/CPSMP2GKT/p1753168967881179
Dette er en sak som er opprettet i forbindelse med en vakt sak der vi kaster feilmelding på en X-SED som ikke har A-SED men har H-SED. Dette blir ikke helt riktig. Har derfor lagt til ekstra kode for å sjekke H-SED i tillegg.
Har også endret variabel navn fra `aSed` til `sed` da jeg er litt usikker det faktisk er A-SED som blir sjekket siden det ikke finnes noe som tyder på det i metodene. Men jeg kan fort ta feil her.
> VAKT Sjekker om HSED også er tom når ASED er tom før vi kaster feilmelding
