Jenkinsfile
naiserator.yaml

Samme endring som på `melosys-app` og `melosys-regler`. Docker registryet docker.adeo.no fases ut, og vi bytter derfor til repo.adeo.no for å kunne fortsette å release fra Jenkins.

Bruk docker registry på repo.adeo.no

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/mapping/MelosysEessiMeldingMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/Adresse.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/Arbeidssted.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/MelosysEessiMelding.java

Første PR i melosys-eessi. Jeg har nok glemt noe viktig.

Arbeidssteder i MelosysEessiMelding for å kunne kontrollere om arbeidssted er Svalbard (MELOSYS-3471)

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/SedDataDto.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxTokenContextService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java
melosys-eessi-app/src/test/resources/mock/sedDataDtoStub.json

Ved (blant annet) utpeking av annet land vil vi kunne sende samme sed til flere utenlandske institusjoner. Venter på implementasjon av dette hos eux.

MELOSYS-3356 - utpeking av annet land

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/SedMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/lovvalg/A009MapperTest.java

erIkkeFastadresse blir ikke satt dersom arbeidssted.fysisk == false/null
Skriver også om på noen tester til å bruke AssertJ.

MELOSYS-3615 - Pkt. 7.1.4 settes ikke i SED A009

---

melosys-eessi-test/pom.xml

- Ikke lag jar, deploy, install for test.

Ikke opprett jar for eessi-test

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/BucinfoDto.java

Relatert til navikt/melosys-api#125

Bruk Set til mottakerinstitusjoner for å unngå duplikater

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedTypeTilTemaMapper.java

Mottatt A003 som faller ut til manuell journalføring skal ha tema medlemskap

MELOSYS-3764 - Mottatt A003 jfr med tema medlemskap

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedTypeTilTemaMapper.java

Reverts navikt/melosys-eessi#209

Revert "MELOSYS-3764 - Mottatt A003 jfr med tema medlemskap"

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java

Kun sett identifikator hvis orgnr er oppgitt i SedDataDto

Identifikator/orgnr er ikke påkrevd for virksomheter i SED

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostFiltype.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/vedlegg/SedMedVedlegg.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostFiltypeTest.java

Oppdater filtyper fra dokarkiv etter MMA-2721

Filtyper oppdatering

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/ArbeidsgiverDeserializer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Nav.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
melosys-eessi-app/src/test/resources/mock/sedH001_medArbeidsgiver.json

SED.Nav.Arbeidsgiver kan forekomme som et enkelt objekt i feks H001. Lager en egen deserialiserer for denne

MELOSYS-3938 - feil ved deserialisering av H001

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A008Mapper.java

Hører med navikt/melosys-api#219

Muliggjør at bostedsadresse kan være null ved opprettelse av SED

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java

Legger til en stygg sleep for å ta høyde for en svakhet i rina som kan føre til at vi ikke kan motta svar på SED vi sendte...... 😢 Kommer av at vi sender SED rett etter vi har opprettet den.
Dette vil heldigvis ikke påvirke brukeropplevelsen, da dette kun vil bli kalt fra saksflyt i melosys-api
Fra Arild:
>Vi har denne feilen (nevnt i en annen tråd) der mottaker kan svare og i tillegg får grønn konvolutt, men der svaret aldri dukker opp i RinaSaken. Sed-en forsvinner mao. Dette skjer fordi Rinasaken ble skadd ved opprettelse og utsending av Sed. En mulig løsning er å legge inn er forsinkelse mellom opprettelse av Sed og utsendelse av Sed. Er det noe som Melosys lett kan gjøre? I Q2 har det fungert å legge inn forsinkelse på 5-6s. I Prod? vet ikke...

Fix for RINA-problematikk

---

melosys-eessi-app/pom.xml
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaConsumerConfig.java
melosys-eessi-test/pom.xml
pom.xml

Bumper spring-versjon samt versjoner for andre mindre biblioteker

Dependency update

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/BucController.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java

Mulighet for å spesifisere om en eventuell eksisterende BUC skal oppdateres hvis mulig ved post-kall mot /buc

---

melosys-eessi-app/pom.xml
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/MelosysEessiApplication.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java

Introduserer spring-retry i et forsøk på å håndtere at opprettelse av BUC i RINA skjer asynkront. Ved kall på "settMottakere" får vi ofte en 404 når det er mye trafikk mot RINA (i arbeidstiden), da BUCen antageligvis ikke har rukket å bli opprettet.

Melosys 4073 opprett buc racecondition

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/MelosysEessiMelding.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/behandling/BehandleSedMottattService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalpostkobling/JournalpostSedKoblingService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/NyttLovvalgEessiMeldingMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/SvarAnmodningUnntakEessiMeldingMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA001Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA002Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA003Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA009Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA010Test.java

Publiserer sedVersjon i MelosysEessiMelding kafka

MELOSYS-4495 - publiser sedversjon på kafka

---

.github/workflows/deploy.yaml
.github/workflows/pull-request.yaml

Samler opp litt dependabot-PRer for å ikke bygge unødvendig mange docker-image ved push på master
Closes #330, closes #328, closes #327

Bump versjoner

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Vedtak.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/VedtakA003.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/VedtakA009.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/LovvalgSedMapper.java

Kom tilfeldigvis over denne ved sjekking av en instans i Q2

Feil ved mapping av tidligere vedtaksdato

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/buc/LukkBucServiceTest.java

...grunnet et misplassert parantes 🙃  Gjort den skyldige sjekken mer lesbart, samt tester akkurat det caset.

Fikser feil ved at melosys-eessi forsøker å lukke alle BUCer som har en update eller create-action

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonIdentifiseringService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/Conversation.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Person.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapper.java

Løser et tilfelle i prod hvor statsborgerskap-listen i en SED inneholdt null-verdier

Listen over statsborgerskap i en SED kan inneholde null-felter

---

.github/workflows/deploy.yaml
melosys-eessi-app/pom.xml
pom.xml

Closes #350 
Closes #346 
Closes #341 
Closes #337
Closes #336 
Closes #334

Oppdaterer eksisterende og rydder i konflikter i transitive avhengigheter

---

.github/workflows/deploy.yaml
.github/workflows/pull-request.yaml
Dockerfile
melosys-eessi-app/pom.xml
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedDataStub.java
pom.xml

Litt kjedelig å måtte bytte mellom 15 og 16 her og i melosys-api 🙃

Bumper til java-16

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/oppgave/OppgaveOppdateringDto.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/Avsender.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/oppgave/OppgaveService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/behandling/SedMottakServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/oppgave/OppgaveServiceTest.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestIT.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/MockData.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedMottakTestIT.java
melosys-eessi-test/src/test/java/no/nav/melosys/utils/KafkaTestConsumer.java

Sjekker person identifisert av ID og fordeling opp mot personen som er mottatt i SED. 
Hvis en person(SED) identifisert av ID og Fordeling har forskjellig statsborgerskap, fødselsdato, kjønn eller utenlandsk-id, så flyttes oppgaven tilbake til deres avdeling, med en tekst som beskriver hva som mangler.

Melosys 4536 kontroller identifisering 2

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonSokMetrikker.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java

Registrerer metrikker etter kontroll av identifisering gjort av ID og fordeling.
Snek inn noe refaktorering på navngivning av metoder....

Melosys 4679 metrikker identifiseringskontroll

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaConsumerConfig.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedSendtConsumer.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/MockData.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedSendtTestIT.java

- Legger til metrikk for feil i journalføring av SED sendt
- Konfigurerer consumer for sedSendt med retry opptil 9 ganger med 5 sekunders delay
- Integrasjonstester for mottak av SED

Melosys 4734 feilhandtering sed sendt

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedHendelse.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/SED.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/repository/SedMottattHendelseRepository.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/MockData.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedMottakTestIT.java

Håndterer aldri X100 SedType, bare journalfører denne

Bugfix-NOJIRA_filterer_bort_X100

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretHendelse.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/oppgave/HentOppgaveDto.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestIT.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/OppgaveEndretMottakTestIT.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedMottakTestIT.java
melosys-eessi-test/src/test/resources/oppgave_endret.json

Legger til håndtering av versjonsnummer på identifiseringsfilter av oppgaven sammenlignet med kafkamelding

Bugfix-NO_JIRA-legger_til_håndtering_av_versjon_mot_oppgave

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
melosys-eessi-app/src/main/resources/application-local.properties
melosys-eessi-app/src/main/resources/application.yml
melosys-eessi-test/src/test/resources/application-test.yaml

Endrer group id for OppgaveEndretConsumer slik at det hentes meldinger fra "earliest"

NO_JIRA-endre-groupid-oppgave-consumer

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/buc/LukkBucService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/buc/LukkBucServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java

Legger til Sedhandling Send sjekk på send sed også

MELOSYS-4766_Validere_om_BUC_er_åpen_før_sending_av_SED-Fiks

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001Mapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009Mapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
melosys-eessi-app/src/test/resources/mock/sedDataDtoStub.json

- Refaktorering
- Filtrer ugyldig statsborgerskap

Filtrer ugyldig statsborgerskap

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java

Valider statsborgerskap finnes

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java

Legger til feature toggle på sjekk mot buc før valideringssjekk.

NO-JIRA_legger_til_toggle_på_eksisterende-buc_sjekk 

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/BucIdentifiseringOppg.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
melosys-eessi-app/src/main/resources/db/migration/V2_4__legger_til_kolonne_buc_identifisering_oppg.sql
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/behandling/SedMottakServiceTest.java

Legger til felt i BucIdentifiseringOppg for å sjekke versjon på identifiseringsoppgave

MELOSYS-4877_legger_til_kolonne_bucidentifiseringsopp_tabell_for_oppgaveendretversjon)

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/Aksjoner.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/eux/EuxService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/eux/EuxServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.java

https://jira.adeo.no/browse/MELOSYS-4766

MELOSYS-4766_sjekker_mulige_handlinger_på_buc_og_sed_før_opprettogsendbuc

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonKontroller.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollServiceTest.java

Statsborgerskap i sed skal også sjekkes mot identifisert person i kontroller

NO_JIRA_statsborgerskap_sjekk_feil_mot_sedperson

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumer.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java

https://github.com/navikt/eux-rina-api/blob/51a2c12dc215b20f5300451771523f08b9a018d7/src/main/java/no/nav/eux/rina/controller/EuxCpiServiceController.java
muligeaksjoner med format=enkelt

Kaller eux med format=enkelt

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/SwaggerConfig.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapperTest.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/KafkaAdminTjenesteTestIT.java
pom.xml

[MELOSYS-5100](https://jira.adeo.no/browse/MELOSYS-5100)
Sjekk også ut
https://nav-it.slack.com/archives/C01BSCJM127/p1649077215195019?thread_ts=1647868923.099209&cid=C01BSCJM127
SpringFox-Swagger2 passet ikke så godt med oppgradert SpringBoot. Oppgraderte til 3.0.0, og fikset med workaround:
`https://github.com/springfox/springfox/issues/3462#issuecomment-1076552144`

Bump Spring Boot 5.4.1 -> 5.6.6

---

Dockerfile
deploy/nais.yaml
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostapiConsumerProducer.java

Det er en Kafka-melding som ikke går an å konsumere fordi vi får OutOfMemoryException. Øker ressurskravet for å prøve å konsumere det offsettet.

Øker ressurskravet for applikasjonen

---

diagrammer/BucIdentifisert.md
diagrammer/SedMottak.dot
diagrammer/SedMottak.md
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestConfig.java

https://jira.adeo.no/browse/MELOSYS-5201
Forsøker å kunne behandle X100 SEDer i melosys. Gjør ingenting med dem hvis det ikke funker (toggle av/på)

5201: Behandler X100 likt som alle andre typer (med toggle)

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaAivenConfig.java

Vi drev og leste på SED for pensjon. Vi skal bare lese på sektorkode LA.
[MELOSYS-4956](https://jira.adeo.no/browse/MELOSYS-4956)

Legger til filter på at vi bare skal konsumere sektorkode LA

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/JournalpostService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/OpprettInngaaendeJournalpostService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/BucIdentifisertEventListener.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertServiceTest.java

https://jira.adeo.no/browse/MELOSYS-5206

Oppretter journalpost med fnr og ikke aktørID

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaAivenConfig.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaConsumerConfig.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedMottattConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedSendtConsumer.java
melosys-eessi-app/src/main/resources/application-local-mock.properties
melosys-eessi-app/src/main/resources/application-local.properties
melosys-eessi-app/src/main/resources/application.yml
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestBase.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/ComponentTestConfig.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/KafkaAdminTjenesteTestIT.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedSendtTestIT.java

Fjerner gamle køer på On Prem som vi fortsatt lytter på. Det produseres ingenting dit lenger, og køen legges sannsynligvis ned snart.
[MELOSYS-4956](https://jira.adeo.no/browse/MELOSYS-4956)

MELOSYS-4956: Fjern gammel konsument

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/MelosysEessiMelding.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/ErOpprinneligVedtakMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA001.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA003.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA009.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA010.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/NyttLovvalgEessiMeldingMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/helpers/ErOpprinneligVedtakMapperTest.java

Ref: https://jira.adeo.no/browse/MELOSYS-5268
* Lagt til erOpprinneligVedtak i A003, A009, og A010 (der vi har Vedtak.java) etter diskusjon med [fag](https://nav-it.slack.com/archives/C01CFP7SL4Q/p1669372416977639).
Det skal ikke være nødvendig med toggle, ettersom dette ikke påvirker noe eksisternde andre steder, før vi tar i bruk dataen vi legger med meldingen.

5268 Lagt til erOpprinneligVedtak i A003, A009, og A010

---

.github/workflows/deploy-dev.yaml

Vi hadde ikke skrevet gruppetilgang-env i deploy-dev. En variabel som går til nais-fila.

5192: Legger til environment om gruppetilgang i deploy-dev.yaml

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Vedtak.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/FraSedA003Mapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA009.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA010.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/sed_grunnlag/SedGrunnlagMapperA003.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/LovvalgSedMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA003Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/melosys_eessi_melding/MelosysEessiMeldingMapperA009Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/sed_grunnlag/SedGrunnlagMapperA003Test.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A003MapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009MapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A010MapperTest.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/MockData.java

Ref: https://jira.adeo.no/browse/MELOSYS-5268
Koden som er endret er allerede under toggle, ved unntak av noe feil som er fikset på data vi sender til Rina.
Dette løser også https://jira.adeo.no/browse/MELOSYS-5514 med at vi sender feil data ut.

5268 TOGGLE logikk fiks for er endring

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaAivenConfig.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedMottattConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedSendtConsumer.java
melosys-eessi-app/src/main/resources/application-local-mock.properties
melosys-eessi-app/src/main/resources/application.yml

Behold eksisterende gruppe id for sent, slik at disse ikke blir re-kjørt.
https://jira.adeo.no/browse/MELOSYS-5612

Lag ny gruppe id for sed mottak

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedMottattConsumer.java

Og ta med alt i sedHendelse ved exception

Log allerede journalført som Warn

---

Dockerfile

https://jira.adeo.no/browse/MELOSYS-5478

5478 navikt/java:17 har flere alvorlige svakheter

---

Dockerfile

Reverts navikt/melosys-eessi#515

Revert "5478 navikt/java:17 har flere alvorlige svakheter"

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java

MELOSYS-5862
https://nav-it.slack.com/archives/CPSMP2GKT/p1681474387007599
Førte til masse feil.

5862: Ikke kontroller XSedBehandletUtenASed hvis X007 og Norge er sakseier

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.java

Fix av #533 funket ikke ettersom vi sjekket mot feil organisasjonsnavn. Bytter nå til organisasjonsid og bruker rinaInstitusjonsId

5862: Sjekk organisasjonsid mot rinaInstitusjonsId

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Grunn.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/InvalideringSed.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Ugyldiggjoere.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerTest.java
melosys-eessi-app/src/test/resources/mock/sedX008.json

https://nav-it.slack.com/archives/CPSMP2GKT/p1681975942363089

4570: Legger til tom konstruktør til DTOs for X008 fordi Jackson trenger det

---

.github/workflows/deploy-dev-manuelt.yaml
.github/workflows/deploy-dev.yaml

[MELOSYS-5874](https://jira.adeo.no/browse/MELOSYS-5874)
Vi har noen applikasjoner i dev-gcp med ingresser som skal slås av 2. mai. Sannsynlig kommer det også for fss etterhvert.
https://nav-it.slack.com/archives/C01DE3M9YBV/p1677747333208699

5874: Bytte ingress for dev-miljø

---

.github/workflows/deploy-dev-manuelt.yaml
.github/workflows/deploy-dev.yaml

Reverter endring av ingress fordi dev-fss støtter ikke intern.dev.nav.no.
Reverts navikt/melosys-eessi#536

Revert "5874: Bytte ingress for dev-miljø"

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/IdentifiseringKontrollService.java

Endrer fra log.error til log.info for SED-er med forskjellig statsborgerskap
https://nav-it.slack.com/archives/C01BSCJM127/p1686120765784589

VAKT Endrer fra log.error til log.info for forskjellig statsborgerskap

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/PersonSok.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/PersonFasade.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/identifisering/PersonSokTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/PDLServiceTest.java

https://unleash.nais.io/#/features/history/melosys.send_til_id_og_fordeling_dersom_ingen_folkeregisterident
https://github.com/navikt/melosys-eessi/pull/549
https://jira.adeo.no/browse/MELOSYS-5963

5963 Fjerner toggles

---

.github/workflows/deploy-dev-manuelt.yaml
.github/workflows/deploy-dev.yaml

https://nav-it.slack.com/archives/CC1HB1C48/p1688629361338759

NOJIRA Legger til slack-melding ved deploy til dev

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedMottattAdminTjeneste.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/OppgaveEndretConsumerGammel.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/OppgaveHendelseConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/SedMottattConsumer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/kafkadlq/KafkaDLQService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/kontroll/SedMottakAdminTjeneste.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/kontroll/SedMottakAdminTjenesteTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.java

Det er for mye støy i loggene nå. Denne var tidligere DEBUG, men gjorde om til infomelding. Etter å prodsette innser jeg det blir for mye støy.
Jeg gjør dette om til DEBUG igjen når jeg fjerner toggle

Melosys 5962:  Logg bak toggle ved oppgaveendring

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/KafkaAivenConfig.java

https://jira.adeo.no/browse/MELOSYS-5962

5962 TOGGLE: Fiks logisk feil på OppgaveHendelse Kafka-filter

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedController.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/joark/OpprettUtgaaendeJournalpostService.java
melosys-eessi-app/src/main/resources/application-local-mock.properties
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/controller/SedControllerTest.java

https://jira.adeo.no/browse/MELOSYS-6024
La til mulighet for å journalføre tilbake i tid via EESSI som har en database som lagrer SEDer dersom de ikke har nok info til å opprette journalposten.

6053 TOGGLE Opprett journalposter tilbake i tid

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/kafkadlq/OppgaveHendelseAivenKafkaDLQ.java

VAKT hotfix for kafka topic

---

.github/workflows/deploy-dev.yaml

...bare for å teste Github actions

NOJIRA: Liten justering på tekst i byggnavn

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapperTest.java

5930 TOGGLE: Bytt fra utenlandskpostsboksadresse til utenlandskvegadresse

---

nais/vars-prod.json
nais/vars-q1.json
nais/vars-q2.json

https://jira.adeo.no/browse/MELOSYS-6110

6110 Env variabler til upper case i vars filer

---

nais/nais.yml

https://docs.nais.io/nais-application/application/#azureapplicationallowallusers

6110 Flyttet feltet allowAllUsers til riktig sted i nais.yml

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/pdl/web/identrekvisisjon/dto/IdentRekvisisjonTilMellomlagringMapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/MockData.java

https://jira.adeo.no/browse/MELOSYS-6201

6201 Fikse fødeland mapping til null for ukjent

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/DatabaseConfig.java

Db rolle er avhengig av DATABASE_NAME og ikke egentlig avhengig av APPLICATION_NAME

6108 Db rolle er avhengig av DATABASE_NAME

---

melosys-eessi-app/src/main/resources/application-local-mock.properties

https://nav-it.slack.com/archives/C01BSCJM127/p1696837362719039?thread_ts=1696494372.302769&cid=C01BSCJM127
Tilhørende oppsett i melosys-api: https://github.com/navikt/melosys-api/pull/2105

NOJIRA Manglende oppsett lokalt

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/helpers/LandkodeMapperTest.java

https://jira.adeo.no/browse/MELOSYS-6305

6305: Map ukjent land til XUK for ISO3 og XU for ISO2

---

nais/unleash-apitoken.yml

https://nav-it.slack.com/archives/CPSMP2GKT/p1701765613819009

VAKT Feil unleash variabel

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.java

https://jira.adeo.no/browse/MELOSYS-6170

6170 Støtte for ukjent land i rina

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java

Blir litt støy som kommer når det står i loggene:
Konverterer fra PDF til PDF. Fjerner denne for pdf

NO_JIRA Endrer logging av konvertering

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostFiltype.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalfoering/JournalpostService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/journalpostapi/JournalpostFiltypeTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/journalfoering/JournalpostServiceTest.java

https://jira.adeo.no/browse/MELOSYS-4500
Fjerner toggle for å konvertere til PDF

4500 Fjern toggle

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/KafkaDLQAdminTjeneste.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/KafkaDLQDto.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/kafkadlq/KafkaDLQ.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/kafkadlq/KafkaDLQService.java
melosys-eessi-app/src/main/resources/db/migration/V5__legger_til_enabled_for_kafka_dlq_kolone.sql

For å hoppe over meldinger som ikke kan kjøres setter skip=true i databasen

Legg til mulighet for å skippe dlq meldinger ved re-kjøring

---

melosys-eessi-app/pom.xml
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/metrikker/MetrikkerNavn.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/metrikker/SedMetrikker.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalfoering/JournalpostService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/journalfoering/JournalpostServiceTest.java
pom.xml

https://jira.adeo.no/browse/MELOSYS-6417

6417 Failer gracefully ved konverteringsfeil til PDF

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/BucIdentifisert.java
melosys-eessi-app/src/main/resources/db/migration/V6__modifiser_unique_rinasaksnummer_kolonne.sql
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/BucIdentifisertConcurrencyIT.java

Legger til Unique constraint til db. Det forhindrer duplicate writes basert på Rinasaksnr
https://jira.adeo.no/browse/MELOSYS-6363

6363 DB duplikater

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/consumers/OppgaveHendelseConsumer.java

Erstatt ident med xxxxxxxxxxx i error logging

6486 Fjerning av logging av ident 

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/featuretoggle/ToggleName.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalpostkobling/JournalpostSedKoblingService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/saksrelasjon/SaksrelasjonService.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/journalpostkobling/JournalpostSedKoblingServiceTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/saksrelasjon/SaksrelasjonServiceTest.java

Beholder lesing hvor lesing brukes før oppdatering av casestore
https://jira.adeo.no/browse/MELOSYS-6427

6427 Legg til toggle for å kunne slå av lesing fra casestore

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/saksrelasjon/SaksrelasjonService.java

https://jira.adeo.no/browse/MELOSYS-6427

6427 Legg til toggle for å kunne slå av lesing og skriving til casestore

---

.github/workflows/codeql.yml

[MELOSYS-6412](https://jira.adeo.no/browse/MELOSYS-6412)

6412 fjern on pull

---

.gitignore
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001Mapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001MapperTest.java

https://jira.adeo.no/browse/MELOSYS-6380

6380 unntak fra lovvalgsland a001

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/ContextHolder.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/UserContextClientRequestInterceptor.java

https://jira.adeo.no/browse/MELOSYS-6530
Lager retry logic for med warning når vi får invalid grant for requests mot EESSI.
Det er uklart nøyaktig hvilke endepunkter som får denne feilen.

6530 hotfix invalid grant type

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/ContextHolder.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/security/UserContextClientRequestInterceptor.java

https://jira.adeo.no/browse/MELOSYS-6530
Utvider canfetchOBOtoken til å sjekke om ident faktisk eksisterer i token.

6530 Sjekk ident for jwt token

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
melosys-eessi-test/src/test/java/no/nav/melosys/eessi/SedSendtTestIT.java

https://jira.adeo.no/browse/MELOSYS-6395
Glemte bygning

6395 DAPI TOGGLE CDM 4.3 tillegsnavn fiks

---

.gitignore
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedJournalføringAdminTjeneste.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/identifisering/BehandleBucIdentifisertService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/repository/SedMottattHendelseRepository.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedJournalføringMigreringRapportDto.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedJournalføringMigreringRapporteringDto.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedJournalføringMigreringService.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedMottattMigreringRapportDto.java
melosys-eessi-app/src/main/resources/application-local-q2.properties

I en uke mens SpringBoot 3 var i prod, ble ingen SED-vedlegg journalført. Vi må derfor kartlegge og journalføre alle vedlegg i den perioden feilen var der.

6601: Journalføring av SED med vedlegg

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PDLConsumerProducer.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/pdl/PdlWebConsumerProducer.java

https://jira.adeo.no/browse/MELOSYS-6557

6557 Behandlingsnummer til PDL

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/journalfoering/OpprettUtgaaendeJournalpostService.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.kt

https://jira.adeo.no/browse/MELOSYS-6794
Bruker samme logikk som for utgående

6654 Bruk samme logikk for inngående som for utgående sed

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/vedlegg/SedMedVedlegg.kt

selv om vedleggene har en tittel i RINA. 
Legg til "Vedlegg" som default.
Se ev. https://nav-it.slack.com/archives/CMHLL7NJY/p1727871266745049?thread_ts=1727855810.420299&cid=CMHLL7NJY

VAKT eux-rina-api gir oss vedlegg med null som tittel

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/jobs/LukkBucJobb.java
melosys-eessi-app/src/main/resources/application-local-mock.properties
melosys-eessi-app/src/main/resources/application.yml
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/jobs/LukkBucJobbTest.java

https://jira.adeo.no/browse/MELOSYS-6910

6910 Lukk buc schedule hentes fra konfig

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java

Om den er null sett vi den til false
https://jira.adeo.no/browse/MELOSYS-6918

6918 harFastArbeidssted kan ikke være null

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/sed/nav/Arbeidsland.kt

https://jira.adeo.no/browse/MELOSYS-6920

6920 hotfix. arbeiddsted er null

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/kafka/producers/model/Arbeidsland.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/buc/BUC.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/integration/eux/rina_api/EuxConsumerSpringTest.kt

https://jira.adeo.no/browse/MELOSYS-6925

6925 bruk tom liste ved null for deserialisering

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/helpers/LandkodeMapperTest.kt

https://jira.adeo.no/browse/MELOSYS-6295
Da funker det å forhåndsvise sed

6295 bruk riktig iso3 kode for kosovo

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/KafkaDLQDto.kt

https://logs.adeo.no/app/discover#/doc/96e648c0-980a-11e9-830a-e17bbd64b4db/.ds-navlogs-2024.11.06-000802?id=2oP1AZMBV3JAD4cHzDEc

PRODFIX KafkaDLQDto builder kan ikke bruke non nullable

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/Adresse.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/Arbeidssted.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/Bruker.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/SedDataDto.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/SedGrunnlagDto.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/dto/Virksomhet.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/fra_sed/sed_grunnlag/SedGrunnlagMapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/X001Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/X008Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/horisontal/HorisontalSedMapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A002Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A003Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A004Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A005Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A008Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A010Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A011Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A012Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/LovvalgSedMapper.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedDataStub.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009MapperTest.java

Rydd i SedMapper og sett non-nullable på de som kaster exception i java koden

6295 Rydd i SedMapper sett non-nullable

---

melosys-eessi-app/pom.xml
melosys-eessi-test/pom.xml
pom.xml

https://jira.adeo.no/browse/MELOSYS-6932

6932 spring boot bump

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/mottak/SedMottakService.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/mottak/SedMottakServiceTest.kt

https://jira.adeo.no/browse/MELOSYS-7000
La til validering av avsender og mottaker for SED.

7000 Melosys skal ikke forsøke å journalføre SED uten nødvendige avsender og mottaker detaljer.

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A008Mapper.kt

Kommer test i egen pr. seinere. (Har lokal test, men er konvertert til Kotlin sammen med flere tester)
https://jira.adeo.no/browse/MELOSYS-7043

7043 A008 må harfastarbeidssted være null om arbeidsland ikke er satt

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/JsonFieldMasker.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/JsonFieldMaskerTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.kt
melosys-eessi-app/src/test/resources/mock/sedDataDtoStub.json
melosys-eessi-app/src/test/resources/mock/sedDataDtoStubMasked.json

Logger sed info ved feil for å letter finne å fikse feil 
Vi masker vekk alt som ikke er i whitelist så ikke sensitiv info blir logget
https://jira.adeo.no/browse/MELOSYS-7043

7043 log masked sed info ved feil

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/config/featuretoggle/ToggleName.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/buc/LukkBucService.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/SedService.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/AdministrativSedMapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/X001Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/X008Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A008Mapper.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/LovvalgSedMapper.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/buc/LukkBucServiceTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedDataStub.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/SedServiceTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/administrativ/X001MapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/horisontal/HorisontalSedMapperTest.java
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A001MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A002MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A003MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A004MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A005MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A008MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A009MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A010MapperTest.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A012MapperTest.kt
melosys-eessi-app/src/test/resources/mock/sedDataDtoStub.json

https://jira.adeo.no/browse/MELOSYS-6394
Glemte å fjerne togglen for 4_3 i eessi. Er gjort i API. API er prodsatt uten toggle, fjerner resten av CDM 4_3 toggle i denne PR.

6394 Fjern CDM 4_3 toggle

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/SedMapper.kt
melosys-eessi-app/src/test/java/no/nav/melosys/eessi/service/sed/mapper/til_sed/lovvalg/A002MapperTest.kt

https://jira.adeo.no/browse/MELOSYS-7121

7121 fjern arbeidsland fra a002

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/integration/journalpostapi/OpprettJournalpostRequestMapper.java
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/models/vedlegg/SedMedVedlegg.kt

Vi har mottatt en SED med tomt vedlegg

VAKT Vi kan motta SED-er med vedlegg uten innhold

---

nais/nais.yml

https://docs.nais.io/observability/logging/how-to/loki/#enable-logging-to-grafana-loki
https://nav-it.slack.com/archives/C01DE3M9YBV/p1744284672614519
Nå støttet for fss også

NOJIRA G4P Legg til logging til Grafana Loki

---

melosys-eessi-app/src/main/java/no/nav/melosys/eessi/controller/SedMottattLagerController.kt
melosys-eessi-app/src/main/java/no/nav/melosys/eessi/repository/SedMottattLagerRepository.kt
melosys-eessi-app/src/main/resources/logback-spring.xml

https://jira.adeo.no/browse/MELOSYS-7403

7403 G4P Legg til SedMottattLagerController
